# 本ソフトウェアは教育目的および研究目的で公開されています。
# このコードの使用、複製、改変、再配布等は利用者の責任において行ってください。
# 開発者は、本コードの使用によって生じたいかなる損害・トラブルについても責任を負いません。
# 本コードの使用が法令や利用規約に抵触しないことを、利用者自身が確認してください。

targetUrl: 'http://abehiroshi.la.coocan.jp/'
delay: 21600000
port: 8080